Repository ministryofjustice/laa-hmrc-interface-service-api, pull requests merged in 2021-08, with the labels that each got.

#91 Update ruby to 3.0.2
  .circleci/config.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: Ready for review

#93 AP-2256: extend smoke tests
  .circleci/config.yml
  README.md
  app/controllers/smoke_test_controller.rb
  app/services/apply_get_test.rb
  app/services/bearer_token.rb
  app/services/smoke_test.rb
  bin/smoke_tests
  config/routes.rb
  config/settings.yml
  config/settings/test.yml
  deploy/helm/templates/_envs.tpl
  deploy/helm/templates/secret.yaml
  deploy/helm/values-uat.yaml
  spec/fixtures/smoke_tests/use_case_four.json
  spec/fixtures/smoke_tests/use_case_three.json
  spec/fixtures/smoke_tests/use_case_two.json
  spec/requests/smoke_test_controller_spec.rb
  spec/services/bearer_token_spec.rb
  spec/services/smoke_test_spec.rb
Labels: Approved

#97 Ap 2255 implement swagger docs
  .idea/dataSources/2d25ab37-17db-4e5b-9056-e84da80db899/entities/entities.dat.len
  .idea/dataSources/2d25ab37-17db-4e5b-9056-e84da80db899/entities/entities.dat_i.len
  .idea/workspace.xml
  Gemfile
  Gemfile.lock
  config/initializers/rswag_api.rb
  config/initializers/rswag_ui.rb
  config/routes.rb
  spec/requests/smoke_test_swagger_spec.rb
  spec/swagger_helper.rb
  swagger/v1/swagger.yaml
Labels: Approved, on-hold

#82 DB delete update
  .circleci/config.yml
  bin/uat_delete_db
  bin/uat_delete_db_setup
  bin/uat_full_db_delete
Labels: Ready for review

#116 AP-2185: Final touch up for staging deploys
  deploy/helm/templates/_envs.tpl
  deploy/helm/templates/secret.yaml
  deploy/helm/values-staging.yaml
Labels: Ready for review

#109 Update swagger test handling
  Gemfile
  README.md
  app/controllers/smoke_test_controller.rb
  spec/requests/smoke_test_controller_spec.rb
  spec/requests/smoke_test_swagger_spec.rb
  swagger/v1/swagger.yaml
Labels: Ready for review

#123 Create submissions model and record submissions to hmrc interface
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/api/V1/use_case_controller.rb
  app/models/submission.rb
  config/routes.rb
  db/migrate/20210826104043_enable_uuid_extension.rb
  db/migrate/20210826104257_create_submissions.rb
  db/schema.rb
  spec/models/submission_spec.rb
  spec/rails_helper.rb
  spec/requests/api/v1/use_case_swagger_spec.rb
  swagger/v1/swagger.yaml
Labels: Approved

#119 AP-2459: Implement S3 storage for results
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  Gemfile.lock
  app/controllers/api/V1/use_case_controller.rb
  app/models/submission.rb
  app/services/apply_get_test.rb
  config/environments/production.rb
  config/storage.yml
  db/migrate/20210831075846_create_active_storage_tables.active_storage.rb
  db/schema.rb
  deploy/helm/templates/_envs.tpl
  spec/models/submission_spec.rb
Labels: Ready for review

#122 API updates
  spec/requests/api/v1/use_case_swagger_spec.rb
  swagger/v1/swagger.yaml
Labels: Ready for review
