Repository ministryofjustice/laa-hmrc-interface-service-api, pull requests merged in 2022-06, with the labels that each got.

#614 Fix: Add Pingom IPs to allow list on prod and staging
  deploy/helm/values-production.yaml
  deploy/helm/values-staging.yaml
Labels: Ready for review

#623 [AP-3184] Clarify authentication requirements
  .github/workflows/delete-uat-release.yml
  bin/uat_drop_db
Labels: Approved

#616 AP-2930 add github action to scan docker images wih snyk
  .github/workflows/docker-image-scan.yml
Labels: Changes requested

#633 Make UAT drop db query more specific
  bin/uat_drop_db
Labels: Approved
